repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    files: '\.yaml$'
  - id: check-json
    files: '\.json$'
  - id: check-xml
    files: '\.xml$'
  - id: check-builtin-literals
  - id: check-ast
  - id: debug-statements

#- repo: local
#  hooks:
#  - id: shellcheck
#    name: shellcheck
#    entry: docker --rm -v "$PWD:/mnt" koalaman/shellcheck:stable
#    language: script
#    types: [shell]
#    args: ['--external-sources']
