#!/bin/bash

_add() {
  local url="${1:?must pass url to add}"
  local name="${url##*/}"
  name="${name%\.git}"
  name="${name%\.vim}"

  grep "$name" .gitmodules && return 0

  #echo git submodule add --name "$name" "$url" ".vim/2btested/$name"
  git submodule add --name "$name" "$url" ".vim/2btested/$name"
}

for u in "$@"; do
  _add "$u"
done

mkreadme > README.md
