#!/bin/bash

git submodule --init --recursive
git config pull.rebase true
git config rebase.autoStash true
git config fetch.recurseSubmodules true
git config fetch.fsckobjects false
git submodule update --checkout
