#[build-syste]
#requires = ["setuptools"]
#build-backend = "setuptools.build_meta"
#
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = 'git-plugin'
version = '0.0.1'
description = 'Manage vim plugins'
dependencies = ['click', 'gitpython', 'giturlparse', 'jinja2']

[project.scripts]
git-plugin = 'git_plugin.cli:cli'
git-plugin-add = 'git_plugin.cli:add'
git-plugin-move = 'git_plugin.cli:move'
git-plugin-remove = 'git_plugin.cli:remove'
git-plugin-readme = 'git_plugin.cli:readme'
git-plugin-learner = 'git_plugin.cli:learner'

[tool.setuptools.packages]
find = {}

[tool.isort]
import_heading_future = "Future Imports"
import_heading_stdlib = "Standard Library Imports"
import_heading_thirdparty = "Third Party Imports"
import_heading_firstparty = "First Party Imports"
import_heading_localfolder = "Local Imports"
length_sort=1
skip_gitignore=1

[tool.pyright]
venv = "venv"
venvPath = "./venv"
reportMissingImports = true
disableOrganizeImports = true

[tool.poetry]
name = "git-plugin"
version = "0.0.1"
description = "Manage submodules for your repository"
authors = ["Alan Young <harleypig@harleypig.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "git_plugin"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.300"
pytest = "^7.2.2"
pytest-pyright = "^0.0.3"
