#!/bin/bash

(($#)) || {
  echo 'Must pass submodule to be removed.' >&2
  exit 1
}

name="$1"

read -r path < <(git config -f .gitmodules --get "submodule.${name}.path")

[[ -z $path ]] && {
  echo "$1 is not a submodule" >&2
  exit 1
}

git rm "$path" || {
  echo "Problem removing $name" >&2
  exit 1
}

mkreadme > README.md
git commit -m "removed $name and updated readme" .gitmodules README.md
rm -fr ".git/modules/${path##*/}"
git config --remove-section "submodule.$name"
